name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'githubActions'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running core tests"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        # with:
        #   dotnet-version: 3.1.x

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - run: dotnet restore ./tst/Tlabs.Core.Tests.csproj

      - run: dotnet test ./tst/Tlabs.Core.Tests.csproj
