name: CI 

on: 
  push:
    branches: 
      - 'githubActions'

jobs:
  Base-tests:
    runs-on: ubuntu-latest
    env:
      cache-name: dotnetcore
    steps:
      - run: echo "Running core tests
      - run: dotnet restore ./tst/Tlabs.Core.Tests.csproj
      - run: dotnet test ./tst/Tlabs.Core.Tests.csproj       
