# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build and Publish NuGet

on:
  workflow_dispatch:

concurrency:
  group: build-and-publish
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  build_and_publish_nuget:
    name: Build and Publish NuGet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

      - name: Checkout shared actions
        uses: actions/checkout@v4
        with:
          repository: tlabster/actions
          path: ./.github/tlabs-actions
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build and Publish NuGet
        uses: ./.github/tlabs-actions/publish-nuget-to-nuget_org
        with:
          context: src
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          nuget_api_key: ${{ secrets.NUGET_APIKEY }}
